import type { ListingConfig } from "../types";

export const carConfig: ListingConfig = {
  type: "car",
  displayName: "Rent a Car",
  steps: [
    {
      id: "details",
      title: "Car Details",
      description:
        "Add your vehicle's make, model, year, and basic specifications.",
      infoAlert:
        "You can find this information on the car registration certificate.",
      submitAction: "create",
      toast: {
        success: "Car details saved.",
        error: "Failed to save car details.",
      },
      fields: [
        {
          name: "car_brand_id",
          label: "Brand",
          type: "select",
          dynamicOptions: "brands",
          required: true,
          span: 1,
        },
        {
          name: "car_model_id",
          label: "Model",
          type: "select",
          dynamicOptions: "models",
          required: true,
          span: 1,
          dependsOn: "car_brand_id",
        },
        {
          name: "plate_number",
          label: "Plate Number",
          type: "text",
          placeholder: "e.g., 34 ABC 123",
          required: true,
          span: 1,
        },
        {
          name: "country_id",
          label: "Country of Registration",
          type: "select",
          dynamicOptions: "countries",
          required: true,
          span: 1,
        },
        {
          name: "year",
          label: "Model Year",
          type: "number",
          placeholder: "e.g., 2023",
          required: true,
          span: 1,
        },
        {
          name: "mileage",
          label: "Mileage (km)",
          type: "number",
          placeholder: "e.g., 50000",
          required: true,
          span: 1,
        },
        {
          name: "fuel_type",
          label: "Fuel Type",
          type: "select",
          options: [
            { value: 1, label: "Petrol" },
            { value: 2, label: "Diesel" },
            { value: 3, label: "Electric" },
            { value: 4, label: "Hybrid" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "about",
          label: "About the Car",
          type: "textarea",
          placeholder: "Describe your car...",
          span: 2,
        },
        {
          name: "transmission_type",
          label: "Transmission",
          type: "radio",
          options: [
            { value: 1, label: "Automatic" },
            { value: 2, label: "Manual" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "number_of_luggage",
          label: "Number of Luggage",
          type: "radio",
          options: [
            { value: 1, label: "1" },
            { value: 2, label: "2" },
            { value: 3, label: "3" },
            { value: 4, label: "4" },
            { value: 5, label: "5" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "number_of_doors",
          label: "Number of Doors",
          type: "radio",
          options: [
            { value: 2, label: "2" },
            { value: 3, label: "3" },
            { value: 4, label: "4" },
            { value: 5, label: "5" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "number_of_seats",
          label: "Number of Seats",
          type: "radio",
          options: [
            { value: 2, label: "2" },
            { value: 4, label: "4" },
            { value: 5, label: "5" },
            { value: 6, label: "6" },
            { value: 7, label: "7+" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "feature_ids",
          label: "Features",
          type: "checkboxGroup",
          dynamicOptions: "features",
          helpText: "Select all features that apply to your car",
          span: 2,
        },
        {
          name: "is_professional_owner",
          label: "Ownership Type",
          type: "radio",
          options: [
            { value: false, label: "Private Owner" },
            { value: true, label: "Professional Owner" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "location_id",
          label: "Check-in Location",
          type: "location",
          helpText: "Where will you meet drivers for check-in?",
          required: true,
          span: 2,
        },
      ],
    },
    {
      id: "pricing",
      title: "Pricing",
      description: "Set rental rates, discounts, and additional fees.",
      infoAlert:
        "We take a 25% service fee from your earnings after each rental.",
      submitAction: "updatePricing",
      toast: {
        success: "Pricing updated.",
        error: "Failed to update pricing.",
      },
      fields: [
        {
          name: "pricing",
          label: "Pricing Configuration",
          type: "custom",
          customComponent: "CarPricing",
          span: 2,
        },
      ],
    },
    {
      id: "media",
      title: "Upload Media",
      description: "Upload high-quality photos of your car inside and out.",
      infoAlert:
        "Cars with more photos get more bookings. We recommend at least 5 photos.",
      submitAction: "uploadMedia",
      toast: {
        success: "Photos uploaded.",
        error: "Failed to upload photos.",
      },
      fields: [
        {
          name: "images",
          label: "Car Photos",
          type: "file",
          required: true,
          helpText: "Upload at least one photo of your car",
          fileConfig: {
            multiple: true,
            maxFiles: 10,
            accept: "image/*",
            existingKey: "existingImages",
            existingLabel: "Existing car photos",
          },
          span: 2,
        },
      ],
    },
    {
      id: "calendar",
      title: "Availability",
      description: "Set when your car is available for rent.",
      submitAction: "updateCalendar",
      toast: {
        success: "Availability updated.",
        error: "Failed to update availability.",
      },
      fields: [
        {
          name: "calendar",
          label: "Availability Calendar",
          type: "custom",
          customComponent: "CarCalendar",
          span: 2,
        },
      ],
    },
    {
      id: "terms",
      title: "Rental Terms",
      description: "Define the terms and conditions for renting your car.",
      submitAction: "updateTerms",
      toast: {
        success: "Terms updated.",
        error: "Failed to update terms.",
      },
      fields: [
        {
          name: "terms",
          label: "Rental Terms",
          type: "custom",
          customComponent: "CarTerms",
          span: 2,
        },
      ],
    },
  ],
  apiEndpoints: {
    create: "/v1/rent-a-car/listings",
    update: "/v1/rent-a-car/listings",
    delete: "/v1/rent-a-car/listings",
    read: "/v1/rent-a-car/listings/:id",
    uploadMedia: "/v1/rent-a-car/listings/{id}/images",
    updatePricing: "/v1/rent-a-car/listings/{id}/pricing",
    updateCalendar: "/v1/rent-a-car/listings/{id}/availability",
    updateTerms: "/v1/rent-a-car/listings/{id}/terms",
  },
};
