import type { ListingConfig } from "../types";

export const hotelConfig: ListingConfig = {
  type: "hotel",
  displayName: "List a Property",
  steps: [
    {
      id: "details",
      title: "Property Details",
      description:
        "Add your property's basic information and location details.",
      infoAlert:
        "Accurate property information helps guests find and book your listing.",
      submitAction: "create",
      fields: [
        {
          name: "propertyName",
          label: "Property Name",
          type: "text",
          placeholder: "e.g., Sunset Beach Hotel",
          required: true,
          span: 2,
        },
        {
          name: "propertyType",
          label: "Property Type",
          type: "select",
          options: [
            { value: 1, label: "Hotel" },
            { value: 2, label: "Apartment" },
            { value: 3, label: "Villa" },
            { value: 4, label: "Hostel" },
            { value: 5, label: "Guest House" },
            { value: 6, label: "Resort" },
            { value: 7, label: "Boutique Hotel" },
          ],
          required: true,
          span: 1,
        },
        {
          name: "starRating",
          label: "Star Rating",
          type: "select",
          options: [
            { value: 1, label: "1 Star" },
            { value: 2, label: "2 Stars" },
            { value: 3, label: "3 Stars" },
            { value: 4, label: "4 Stars" },
            { value: 5, label: "5 Stars" },
            { value: 0, label: "Unrated" },
          ],
          required: true,
          span: 1,
        },
        {
          name: "locationId",
          label: "Property Location",
          type: "location",
          helpText: "Pin the exact location of your property",
          required: true,
          span: 2,
        },
        {
          name: "address",
          label: "Street Address",
          type: "text",
          placeholder: "e.g., 123 Beach Road",
          required: true,
          span: 2,
        },
        {
          name: "city_id",
          label: "City",
          type: "select",
          dynamicOptions: "cities",
          required: true,
          span: 1,
        },
        {
          name: "country_id",
          label: "Country",
          type: "select",
          dynamicOptions: "countries",
          required: true,
          span: 1,
        },
        {
          name: "zipCode",
          label: "Postal/ZIP Code",
          type: "text",
          placeholder: "e.g., 12345",
          span: 1,
        },
        {
          name: "totalFloors",
          label: "Number of Floors",
          type: "number",
          placeholder: "e.g., 5",
          span: 1,
        },
        {
          name: "description",
          label: "Property Description",
          type: "textarea",
          placeholder:
            "Describe your property, its unique features, and what makes it special...",
          required: true,
          span: 2,
        },
        {
          name: "amenityIds",
          label: "Property Amenities",
          type: "checkboxGroup",
          dynamicOptions: "hotelAmenities",
          helpText: "Select all amenities available at your property",
          span: 2,
        },
        {
          name: "languagesSpoken",
          label: "Languages Spoken",
          type: "checkboxGroup",
          dynamicOptions: "languages",
          helpText: "Languages spoken by your staff",
          span: 2,
        },
      ],
    },
    {
      id: "rooms",
      title: "Add Rooms",
      description:
        "Define the different room types available at your property.",
      infoAlert:
        "You can add multiple room types. Each room type can have multiple units.",
      submitAction: "update",
      fields: [
        {
          name: "rooms",
          label: "Room Configuration",
          type: "custom",
          customComponent: "HotelRooms",
          span: 2,
        },
      ],
    },
    {
      id: "media",
      title: "Upload Media",
      description: "Upload high-quality photos of your property and rooms.",
      infoAlert:
        "Properties with professional photos get 3x more bookings. Include photos of rooms, amenities, and exterior.",
      submitAction: "uploadMedia",
      fields: [
        {
          name: "propertyImages",
          label: "Property Photos",
          type: "file",
          required: true,
          helpText:
            "Upload photos of your property exterior, lobby, and common areas",
          fileConfig: {
            multiple: true,
            maxFiles: 20,
            accept: "image/*",
          },
          span: 2,
        },
        {
          name: "roomImages",
          label: "Room Photos",
          type: "file",
          required: true,
          helpText: "Upload photos of different room types",
          fileConfig: {
            multiple: true,
            maxFiles: 20,
            accept: "image/*",
          },
          span: 2,
        },
      ],
    },
    {
      id: "pricing",
      title: "Pricing & Seasons",
      description: "Set base rates and seasonal pricing for your rooms.",
      infoAlert:
        "We take a 15% service fee from your earnings after each booking.",
      submitAction: "updatePricing",
      fields: [
        {
          name: "pricing",
          label: "Pricing Configuration",
          type: "custom",
          customComponent: "HotelPricing",
          span: 2,
        },
      ],
    },
    {
      id: "availability",
      title: "Availability",
      description: "Manage room availability and block dates when needed.",
      submitAction: "update",
      fields: [
        {
          name: "calendar",
          label: "Availability Calendar",
          type: "custom",
          customComponent: "HotelCalendar",
          span: 2,
        },
        {
          name: "minimumStay",
          label: "Minimum Stay (nights)",
          type: "number",
          placeholder: "e.g., 1",
          helpText: "Minimum number of nights guests must book",
          required: true,
          span: 1,
        },
        {
          name: "maximumStay",
          label: "Maximum Stay (nights)",
          type: "number",
          placeholder: "e.g., 30",
          helpText:
            "Maximum number of nights guests can book (leave empty for no limit)",
          span: 1,
        },
      ],
    },
    {
      id: "policies",
      title: "Policies & Rules",
      description:
        "Define check-in/out times, cancellation policy, and house rules.",
      submitAction: "update",
      fields: [
        {
          name: "checkInTime",
          label: "Check-in Time",
          type: "time",
          required: true,
          span: 1,
        },
        {
          name: "checkOutTime",
          label: "Check-out Time",
          type: "time",
          required: true,
          span: 1,
        },
        {
          name: "cancellationPolicy",
          label: "Cancellation Policy",
          type: "select",
          options: [
            {
              value: 1,
              label: "Flexible - Full refund 24 hours before check-in",
            },
            {
              value: 2,
              label: "Moderate - Full refund 5 days before check-in",
            },
            { value: 3, label: "Strict - 50% refund 7 days before check-in" },
            { value: 4, label: "Non-refundable" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "petsAllowed",
          label: "Pets Allowed",
          type: "radio",
          options: [
            { value: true, label: "Yes" },
            { value: false, label: "No" },
          ],
          required: true,
          span: 1,
        },
        {
          name: "smokingAllowed",
          label: "Smoking Allowed",
          type: "radio",
          options: [
            { value: true, label: "Yes" },
            { value: false, label: "No" },
          ],
          required: true,
          span: 1,
        },
        {
          name: "childrenAllowed",
          label: "Children Allowed",
          type: "radio",
          options: [
            { value: true, label: "Yes" },
            { value: false, label: "No" },
          ],
          required: true,
          span: 1,
        },
        {
          name: "partiesAllowed",
          label: "Parties/Events Allowed",
          type: "radio",
          options: [
            { value: true, label: "Yes" },
            { value: false, label: "No" },
          ],
          required: true,
          span: 1,
        },
        {
          name: "houseRules",
          label: "Additional House Rules",
          type: "textarea",
          placeholder: "Add any additional rules or policies for guests...",
          helpText: "Quiet hours, visitor policy, etc.",
          span: 2,
        },
        {
          name: "paymentMethods",
          label: "Accepted Payment Methods",
          type: "checkboxGroup",
          options: [
            { value: 1, label: "Credit Card" },
            { value: 2, label: "Debit Card" },
            { value: 3, label: "Cash" },
            { value: 4, label: "Bank Transfer" },
            { value: 5, label: "PayPal" },
          ],
          required: true,
          span: 2,
        },
      ],
    },
    {
      id: "contact",
      title: "Contact Information",
      description: "Add contact details for guest inquiries.",
      submitAction: "update",
      fields: [
        {
          name: "contactName",
          label: "Contact Person",
          type: "text",
          placeholder: "e.g., John Smith",
          required: true,
          span: 1,
        },
        {
          name: "phoneNumber",
          label: "Phone Number",
          type: "tel",
          placeholder: "e.g., +1 234 567 8900",
          required: true,
          span: 1,
        },
        {
          name: "email",
          label: "Email Address",
          type: "email",
          placeholder: "e.g., info@hotel.com",
          required: true,
          span: 1,
        },
        {
          name: "website",
          label: "Website (optional)",
          type: "text",
          placeholder: "e.g., https://www.hotel.com",
          span: 1,
        },
        {
          name: "emergencyContact",
          label: "24/7 Emergency Contact",
          type: "tel",
          placeholder: "e.g., +1 234 567 8999",
          required: true,
          span: 2,
        },
      ],
    },
  ],
  apiEndpoints: {
    create: "/api/proxy/Hotels",
    update: "/api/proxy/Hotels",
    delete: "/api/proxy/Hotels",
    read: "/api/proxy/Hotels",
    uploadMedia: "/api/proxy/Hotels/{id}/images",
    updateRooms: "/api/proxy/Hotels/{id}/rooms",
    updatePricing: "/api/proxy/Hotels/{id}/pricing",
    updateAvailability: "/api/proxy/Hotels/{id}/availability",
    updatePolicies: "/api/proxy/Hotels/{id}/policies",
    updateContact: "/api/proxy/Hotels/{id}/contact",
  },
};
