import type { ListingConfig } from "../types";

export const transferConfig: ListingConfig = {
  type: "transfer",
  displayName: "Add Transfer Service",
  steps: [
    {
      id: "vehicle",
      title: "Vehicle Details",
      description:
        "Enter your vehicle's make, model, year, and specifications.",
      infoAlert:
        "You can find this information on the vehicle registration certificate.",
      submitAction: "create",
      toast: {
        success: "Vehicle details saved.",
        error: "Failed to save vehicle details.",
      },
      fields: [
        {
          name: "vehicle_brand_id",
          label: "Brand",
          type: "select",
          dynamicOptions: "brands",
          required: true,
          span: 1,
        },
        {
          name: "car_model_id",
          label: "Model",
          type: "select",
          dynamicOptions: "models",
          required: true,
          span: 1,
          dependsOn: "vehicle_brand_id",
        },
        {
          name: "plate_number",
          label: "Plate number",
          type: "text",
          placeholder: "e.g., 34 ABC 123",
          required: true,
          span: 1,
        },
        {
          name: "country_id",
          label: "Country of registration",
          type: "select",
          dynamicOptions: "countries",
          required: true,
          span: 1,
        },
        {
          name: "car_model_year",
          label: "Car model year",
          type: "number",
          placeholder: "e.g., 2023",
          required: true,
          span: 1,
        },
        {
          name: "mileage",
          label: "Mileage (km)",
          type: "number",
          placeholder: "e.g., 50000",
          required: true,
          span: 1,
        },
        {
          name: "fuel_type",
          label: "Fuel",
          type: "select",
          options: [
            { value: 1, label: "Petrol" },
            { value: 2, label: "Diesel" },
            { value: 3, label: "Electric" },
            { value: 4, label: "Hybrid" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "transmission_type",
          label: "Transmission",
          type: "radio",
          options: [
            { value: 1, label: "Manual" },
            { value: 2, label: "Automatic" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "number_of_doors",
          label: "Number of doors",
          type: "radio",
          options: [
            { value: 2, label: "2" },
            { value: 3, label: "3" },
            { value: 4, label: "4" },
            { value: 5, label: "5" },
            { value: 6, label: "6" },
            { value: 7, label: "7+" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "number_of_seats",
          label: "Number of seats",
          type: "radio",
          options: [
            { value: 2, label: "2" },
            { value: 3, label: "3" },
            { value: 4, label: "4" },
            { value: 5, label: "5" },
            { value: 6, label: "6" },
            { value: 7, label: "7+" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "number_of_luggage",
          label: "Number of luggage",
          type: "radio",
          options: [
            { value: 2, label: "2" },
            { value: 3, label: "3" },
            { value: 4, label: "4" },
            { value: 5, label: "5" },
            { value: 6, label: "6" },
            { value: 7, label: "7+" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "feature_ids",
          label: "Features",
          type: "checkboxGroup",
          dynamicOptions: "features",
          helpText: "Select all features that apply to your vehicle",
          span: 2,
        },
        {
          name: "is_professional_owner",
          label: "Ownership",
          type: "radio",
          options: [
            { value: false, label: "No, I'm a private owner" },
            { value: true, label: "Yes, I'm a professional owner" },
          ],
          required: true,
          span: 2,
        },
      ],
    },
    {
      id: "service",
      title: "Service Information",
      description: "Define your transfer service details and coverage areas.",
      infoAlert:
        "Clear service information helps customers understand your offerings.",
      submitAction: "updateService",
      fields: [
        {
          name: "service_name",
          label: "Service Name",
          type: "text",
          placeholder: "e.g., Airport VIP Transfer",
          required: true,
          span: 2,
        },
        {
          name: "service_type",
          label: "Service Type",
          type: "checkboxGroup",
          options: [
            { value: 1, label: "Airport Transfer" },
            { value: 2, label: "Hotel Transfer" },
            { value: 3, label: "City Transfer" },
            { value: 4, label: "Intercity Transfer" },
            { value: 5, label: "Event Transfer" },
            { value: 6, label: "Hourly Charter" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "pickup_locations",
          label: "Pickup Locations",
          type: "custom",
          customComponent: "LocationPicker",
          helpText: "Add all locations where you can pick up customers",
          required: true,
          span: 2,
        },
        {
          name: "dropoff_locations",
          label: "Drop-off Locations",
          type: "custom",
          customComponent: "LocationPicker",
          helpText: "Add all locations where you can drop off customers",
          required: true,
          span: 2,
        },
        {
          name: "service_area",
          label: "Service Area",
          type: "select",
          dynamicOptions: "serviceAreas",
          helpText: "Primary service area or city",
          required: true,
          span: 1,
        },
        {
          name: "max_travel_distance",
          label: "Maximum Travel Distance (km)",
          type: "number",
          placeholder: "e.g., 200",
          helpText: "Leave empty for unlimited",
          span: 1,
        },
        {
          name: "operating_hours",
          label: "Operating Hours",
          type: "radio",
          options: [
            { value: 1, label: "24/7 Service" },
            { value: 2, label: "Custom Hours" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "custom_hours",
          label: "Custom Operating Hours",
          type: "custom",
          customComponent: "OperatingHours",
          helpText: "Set specific hours for each day",
          span: 2,
          dependsOn: "operating_hours",
        },
        {
          name: "advance_booking_required",
          label: "Advance Booking Required",
          type: "number",
          placeholder: "e.g., 2",
          helpText: "Minimum hours before pickup",
          required: true,
          span: 1,
        },
        {
          name: "instant_booking",
          label: "Instant Booking",
          type: "radio",
          options: [
            { value: true, label: "Yes - Automatic confirmation" },
            { value: false, label: "No - Manual confirmation required" },
          ],
          required: true,
          span: 2,
        },
      ],
    },
    {
      id: "driver",
      title: "Driver Information",
      description: "Add details about drivers providing the service.",
      infoAlert: "Professional driver information builds trust with customers.",
      submitAction: "updateDriver",
      fields: [
        {
          name: "driver_name",
          label: "Driver Name",
          type: "text",
          placeholder: "e.g., John Smith",
          required: true,
          span: 1,
        },
        {
          name: "driver_phone",
          label: "Driver Phone",
          type: "tel",
          placeholder: "e.g., +1 234 567 8900",
          required: true,
          span: 1,
        },
        {
          name: "license_number",
          label: "Driver License Number",
          type: "text",
          placeholder: "e.g., DL123456789",
          required: true,
          span: 1,
        },
        {
          name: "years_of_experience",
          label: "Years of Experience",
          type: "number",
          placeholder: "e.g., 5",
          required: true,
          span: 1,
        },
        {
          name: "languages_spoken",
          label: "Languages Spoken",
          type: "checkboxGroup",
          dynamicOptions: "languages",
          helpText: "Select all languages the driver speaks",
          required: true,
          span: 2,
        },
        {
          name: "driver_features",
          label: "Driver Qualifications",
          type: "checkboxGroup",
          options: [
            { value: 1, label: "Professional Uniform" },
            { value: 2, label: "Airport Permit" },
            { value: 3, label: "Hotel Permit" },
            { value: 4, label: "First Aid Certified" },
            { value: 5, label: "Tourism License" },
            { value: 6, label: "Defensive Driving Certified" },
          ],
          span: 2,
        },
        {
          name: "driver_bio",
          label: "Driver Bio",
          type: "textarea",
          placeholder:
            "Tell customers about the driver's experience and professionalism...",
          span: 2,
        },
      ],
    },
    {
      id: "pricing",
      title: "Pricing",
      description: "Set your transfer rates and pricing structure.",
      infoAlert:
        "We take a 20% service fee from your earnings after each transfer.",
      submitAction: "updatePricing",
      fields: [
        {
          name: "pricing_type",
          label: "Pricing Model",
          type: "radio",
          options: [
            { value: 1, label: "Flat Rate" },
            { value: 2, label: "Per Kilometer" },
            { value: 3, label: "Per Hour" },
            { value: 4, label: "Custom Routes" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "pricing",
          label: "Pricing Configuration",
          type: "custom",
          customComponent: "TransferPricing",
          span: 2,
        },
        {
          name: "waiting_time_charge",
          label: "Waiting Time Charge (per 15 min)",
          type: "number",
          placeholder: "e.g., 5",
          helpText: "Additional charge if driver needs to wait",
          span: 1,
        },
        {
          name: "meet_and_greet_fee",
          label: "Meet & Greet Fee",
          type: "number",
          placeholder: "e.g., 10",
          helpText: "Optional fee for airport/hotel pickup with sign",
          span: 1,
        },
        {
          name: "extra_luggage_fee",
          label: "Extra Luggage Fee (per item)",
          type: "number",
          placeholder: "e.g., 3",
          helpText: "Charge for luggage exceeding capacity",
          span: 1,
        },
        {
          name: "child_seat_fee",
          label: "Child Seat Fee",
          type: "number",
          placeholder: "e.g., 8",
          helpText: "Fee per child seat",
          span: 1,
        },
        {
          name: "cancellation_policy",
          label: "Cancellation Policy",
          type: "select",
          options: [
            { value: 1, label: "Free cancellation 24h before" },
            { value: 2, label: "Free cancellation 12h before" },
            { value: 3, label: "Free cancellation 6h before" },
            { value: 4, label: "50% refund up to 24h before" },
            { value: 5, label: "Non-refundable" },
          ],
          required: true,
          span: 2,
        },
      ],
    },
    {
      id: "media",
      title: "Upload Media",
      description: "Upload photos of your vehicle and service.",
      infoAlert:
        "Quality photos increase bookings. Include exterior, interior, and driver photos.",
      submitAction: "uploadMedia",
      fields: [
        {
          name: "vehicle_images",
          label: "Vehicle Photos",
          type: "file",
          required: true,
          helpText: "Upload photos of your vehicle from different angles",
          fileConfig: {
            multiple: true,
            maxFiles: 10,
            accept: "image/*",
          },
          span: 2,
        },
        {
          name: "driver_photo",
          label: "Driver Photo",
          type: "file",
          helpText: "Professional photo of the driver (optional)",
          fileConfig: {
            multiple: false,
            maxFiles: 1,
            accept: "image/*",
          },
          span: 2,
        },
      ],
    },
    {
      id: "extras",
      title: "Extra Services",
      description: "Add optional services and amenities you can provide.",
      submitAction: "updateExtras",
      fields: [
        {
          name: "extra_services",
          label: "Available Extras",
          type: "checkboxGroup",
          options: [
            { value: 1, label: "WiFi" },
            { value: 2, label: "Bottled Water" },
            { value: 3, label: "Newspapers/Magazines" },
            { value: 4, label: "Phone Chargers" },
            { value: 5, label: "Child Seats Available" },
            { value: 6, label: "Pet Friendly" },
            { value: 7, label: "Wheelchair Accessible" },
            { value: 8, label: "Refreshments" },
          ],
          span: 2,
        },
        {
          name: "special_requests",
          label: "Special Requests Accepted",
          type: "radio",
          options: [
            { value: true, label: "Yes - I can accommodate special requests" },
            { value: false, label: "No" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "special_requests_note",
          label: "Special Requests Guidelines",
          type: "textarea",
          placeholder:
            "Explain what kind of special requests you can handle...",
          helpText: "e.g., multiple stops, specific routes, etc.",
          span: 2,
          dependsOn: "special_requests",
        },
      ],
    },
    {
      id: "terms",
      title: "Terms & Conditions",
      description: "Set rules and requirements for your transfer service.",
      submitAction: "updateTerms",
      fields: [
        {
          name: "minimum_age",
          label: "Minimum Age for Solo Passengers",
          type: "number",
          placeholder: "e.g., 18",
          helpText: "Minimum age to book without a guardian",
          span: 1,
        },
        {
          name: "payment_method",
          label: "Accepted Payment Methods",
          type: "checkboxGroup",
          options: [
            { value: 1, label: "Cash" },
            { value: 2, label: "Credit Card" },
            { value: 3, label: "Debit Card" },
            { value: 4, label: "Online Payment" },
            { value: 5, label: "Bank Transfer" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "payment_timing",
          label: "Payment Timing",
          type: "radio",
          options: [
            { value: 1, label: "Pay Online in Advance" },
            { value: 2, label: "Pay Driver After Service" },
            { value: 3, label: "Both Options Available" },
          ],
          required: true,
          span: 2,
        },
        {
          name: "smoking_allowed",
          label: "Smoking Allowed",
          type: "radio",
          options: [
            { value: false, label: "No Smoking" },
            { value: true, label: "Smoking Allowed" },
          ],
          required: true,
          span: 1,
        },
        {
          name: "pets_allowed",
          label: "Pets Allowed",
          type: "radio",
          options: [
            { value: false, label: "No Pets" },
            { value: true, label: "Pets Allowed" },
          ],
          required: true,
          span: 1,
        },
        {
          name: "luggage_policy",
          label: "Luggage Policy",
          type: "textarea",
          placeholder: "Describe your luggage policy and any restrictions...",
          helpText: "e.g., size limits, oversize fees, etc.",
          span: 2,
        },
        {
          name: "additional_terms",
          label: "Additional Terms & Conditions",
          type: "textarea",
          placeholder: "Add any additional terms customers should know...",
          span: 2,
        },
      ],
    },
  ],
  apiEndpoints: {
    create: "/v1/transfers/listings",
    update: "/v1/transfers/listings",
    delete: "/v1/transfers/listings",
    read: "/v1/transfers/listings/:id",
    uploadMedia: "/v1/transfers/listings/{id}/images",
    updateService: "/v1/transfers/listings/{id}/service",
    updateDriver: "/v1/transfers/listings/{id}/driver",
    updatePricing: "/v1/transfers/listings/{id}/pricing",
    updateExtras: "/v1/transfers/listings/{id}/extras",
    updateTerms: "/v1/transfers/listings/{id}/terms",
  },
};
