import type { FilterConfig } from "../types";

export const hotelFilterConfig: FilterConfig = {
  type: "hotel",
  displayName: "Filter Properties",
  fields: [
    {
      name: "country_id",
      label: "Country",
      type: "custom",
      customComponent: "CountrySelect",
      placeholder: "Select country",
      span: 1,
    },
    {
      name: "city_id",
      label: "City",
      type: "custom",
      customComponent: "CitySelect",
      placeholder: "Select city",
      span: 1,
      dependsOn: "country_id",
    },
    {
      name: "propertyType",
      label: "Property Type",
      type: "select",
      options: [
        { value: 1, label: "Hotel" },
        { value: 2, label: "Apartment" },
        { value: 3, label: "Villa" },
        { value: 4, label: "Hostel" },
        { value: 5, label: "Guest House" },
        { value: 6, label: "Resort" },
        { value: 7, label: "Boutique Hotel" },
      ],
      placeholder: "Select type",
      span: 2,
    },
    {
      name: "starRating",
      label: "Star Rating",
      type: "chips",
      chipOptions: ["1", "2", "3", "4", "5"],
      span: 2,
    },
    {
      name: "price",
      label: "Price Range (per night)",
      type: "range",
      minField: "price_min",
      maxField: "price_max",
      span: 2,
    },
    {
      name: "dates",
      label: "Stay Dates",
      type: "dateRange",
      minField: "check_in",
      maxField: "check_out",
      span: 2,
    },
    {
      name: "amenities",
      label: "Amenities",
      type: "select",
      dynamicOptions: "hotelAmenities",
      placeholder: "Select amenities",
      span: 2,
    },
    {
      name: "sort_by",
      label: "Sort By",
      type: "select",
      options: [
        { value: "created_at", label: "Newest First" },
        { value: "price_low", label: "Price: Low to High" },
        { value: "price_high", label: "Price: High to Low" },
        { value: "rating", label: "Rating" },
      ],
      placeholder: "Sort by",
      span: 1,
    },
    {
      name: "sort_order",
      label: "Sort Order",
      type: "select",
      options: [
        { value: "desc", label: "Descending" },
        { value: "asc", label: "Ascending" },
      ],
      placeholder: "Order",
      span: 1,
    },
  ],
  defaultValues: {
    country_id: null,
    city_id: null,
    propertyType: null,
    starRating: null,
    price_min: "",
    price_max: "",
    check_in: null,
    check_out: null,
    amenities: null,
    sort_by: "created_at",
    sort_order: "desc",
  },
};
