import type { FilterConfig } from "../types";

export const transferFilterConfig: FilterConfig = {
  type: "transfer",
  displayName: "Filter Transfers",
  fields: [
    {
      name: "country_id",
      label: "Country",
      type: "custom",
      customComponent: "CountrySelect",
      placeholder: "Select country",
      span: 1,
    },
    {
      name: "brand_id",
      label: "Vehicle Brand",
      type: "custom",
      customComponent: "BrandSelect",
      placeholder: "Select brand",
      span: 1,
    },
    {
      name: "service_type",
      label: "Service Type",
      type: "select",
      options: [
        { value: 1, label: "Airport Transfer" },
        { value: 2, label: "Hotel Transfer" },
        { value: 3, label: "City Transfer" },
        { value: 4, label: "Intercity Transfer" },
        { value: 5, label: "Event Transfer" },
        { value: 6, label: "Hourly Charter" },
      ],
      placeholder: "Select service type",
      span: 2,
    },
    {
      name: "number_of_seats",
      label: "Number of Seats",
      type: "chips",
      chipOptions: ["2", "4", "5", "6", "7+"],
      span: 2,
    },
    {
      name: "fuel_type",
      label: "Fuel Type",
      type: "select",
      options: [
        { value: 1, label: "Petrol" },
        { value: 2, label: "Diesel" },
        { value: 3, label: "Electric" },
        { value: 4, label: "Hybrid" },
      ],
      placeholder: "Select fuel type",
      span: 1,
    },
    {
      name: "transmission_type",
      label: "Transmission",
      type: "select",
      options: [
        { value: 1, label: "Manual" },
        { value: 2, label: "Automatic" },
      ],
      placeholder: "Select transmission",
      span: 1,
    },
    {
      name: "price",
      label: "Price Range",
      type: "range",
      minField: "price_min",
      maxField: "price_max",
      span: 2,
    },
    {
      name: "transfer_date",
      label: "Transfer Date",
      type: "date",
      placeholder: "Select date",
      span: 2,
    },
    {
      name: "sort_by",
      label: "Sort By",
      type: "select",
      options: [
        { value: "created_at", label: "Newest First" },
        { value: "price_low", label: "Price: Low to High" },
        { value: "price_high", label: "Price: High to Low" },
        { value: "rating", label: "Rating" },
      ],
      placeholder: "Sort by",
      span: 1,
    },
    {
      name: "sort_order",
      label: "Sort Order",
      type: "select",
      options: [
        { value: "desc", label: "Descending" },
        { value: "asc", label: "Ascending" },
      ],
      placeholder: "Order",
      span: 1,
    },
  ],
  defaultValues: {
    country_id: null,
    brand_id: null,
    service_type: null,
    number_of_seats: null,
    fuel_type: null,
    transmission_type: null,
    price_min: "",
    price_max: "",
    transfer_date: null,
    sort_by: "created_at",
    sort_order: "desc",
  },
};
